# Project information
site_name: DT-GEO WP6 Tsunamis documentation
site_url: https://dtgeoeu-wp6-tsunamis.github.io/dt-geo-wp6-docs/
site_author: Sunniva Indrehus
site_description: >-
  Instructions for the tools and codes used by DT-GEO WP6 Tsunamis


# Repository
repo_name: dtgeoeu-wp6-tsunamis/dt-geo-wp6-docs
repo_url: https://github.com/dtgeoeu-wp6-tsunamis/dt-geo-wp6-docs
theme:
  logo: images/logo-dt-geo-wp6.png
  favicon: images/logo-dt-geo-wp6.png
  palette:
      primary: blue
      accent: deep orange
  name: material
  custom_dir: overrides
  features:
    - search.suggest    # display the likeliest completion for the last word
    - search.highlight  # highlight all occurrences
    - search.share      # show a share button
    - navigation.footer
    - navigation.indexes
    - content.code.copy
    - content.code.annotate
    - announce.dismiss
    - header.autohide
extra_css:
  - stylesheets/extra.css
plugins:
    - search
    - awesome-pages
markdown_extensions:
  - footnotes
  - admonition
  - mdx_math
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
